//
//  RandomUsers App
//  Created by Freek (github.com/frzi) 2021
//

import Foundation
import MapKit
import SwiftUI

struct UserLocationScreen: View {
	let location: UserModel.Location
	
	@State private var uuid = UUID()
	@State private var mapCamera: MapCameraPosition

	init(location: UserModel.Location) {
		self._mapCamera = State(
			initialValue: .camera(MapCamera(
				centerCoordinate: location.coordinates.clLocation,
				distance: 1e4
			))
		)

		self.location = location
	}
	
	var body: some View {
		ZStack(alignment: .topTrailing) {
			Map(position: $mapCamera) {
				Marker(coordinate: location.coordinates.clLocation) {
					Text("Labeltje")
				}
			}

			Text("*Note:* coordinates generated by randomuser.me tend to be pretty bogus.")
				.foregroundColor(.white)
				.padding(6)
				.background(Color.black.opacity(0.5))
		}
		.background(Color.white)
	}
}
