//
//  RandomUsers App
//  Created by Freek (github.com/frzi) 2021
//

import Foundation
import MapKit
import SwiftUI

struct UserLocationScreen: View {
	let location: UserModel.Location
	
	@State private var uuid = UUID()
	@State private var region: MKCoordinateRegion
	@State private var mapCamera: MapCameraPosition

	init(location: UserModel.Location) {
		self._region = State(initialValue: MKCoordinateRegion(
			center: location.coordinates.clLocation,
			latitudinalMeters: 1e4,
			longitudinalMeters: 1e4
		))

		self._mapCamera = State(
			initialValue: .camera(MapCamera(centerCoordinate: location.coordinates.clLocation, distance: 1e4))
		)

		self.location = location
	}
	
	private var pin: LocationPin {
		LocationPin(id: uuid, location: location.coordinates.clLocation)
	}
	
	var body: some View {
		ZStack(alignment: .topTrailing) {
//			Map(coordinateRegion: $region, annotationItems: [pin]) { pin in
//				MapPin(coordinate: pin.location, tint: .blue)
//			}

			Map(position: $mapCamera) {
				Marker(coordinate: pin.location) {
					Text("Labeltje")
				}
			}

			Text("*Note:* coordinates generated by randomuser.me tend to be pretty bogus.")
				.foregroundColor(.white)
				.padding(6)
				.background(Color.black.opacity(0.5))
		}
		.background(Color.white)
	}
	
	private struct LocationPin: Identifiable {
		let id: UUID
		let location: CLLocationCoordinate2D
	}
}
